const { withMainActivity, CodeGenerator } = require("@expo/config-plugins");

const { mergeContents } = CodeGenerator;

const IMPORT_TAG = "health-connect-permission-delegate-import";
const CALL_TAG = "health-connect-permission-delegate-call";

/**
 * react-native-health-connect's requestPermission() crashes at runtime
 * (kotlin.UninitializedPropertyAccessException: lateinit property
 * requestPermission has not been initialized) unless
 * HealthConnectPermissionDelegate.setPermissionDelegate(this) runs in
 * MainActivity.onCreate(). The library's own Expo config plugin only
 * patches AndroidManifest.xml, never MainActivity — see
 * https://github.com/matinzd/react-native-health-connect/issues/114.
 * This project has no committed native android/, so MainActivity.kt is
 * regenerated by every prebuild/EAS build; this plugin re-applies the fix
 * each time.
 */
function applyHealthConnectPermissionDelegate(contents) {
  contents = mergeContents({
    src: contents,
    newSrc: "import dev.matinzd.healthconnect.permissions.HealthConnectPermissionDelegate",
    tag: IMPORT_TAG,
    anchor: /^import android\.os\.Bundle$/m,
    offset: 1,
    comment: "//",
  }).contents;

  contents = mergeContents({
    src: contents,
    newSrc: "    HealthConnectPermissionDelegate.setPermissionDelegate(this)",
    tag: CALL_TAG,
    anchor: /super\.onCreate\(/,
    offset: 1,
    comment: "//",
  }).contents;

  return contents;
}

function withHealthConnectPermissionDelegate(config) {
  return withMainActivity(config, (config) => {
    if (config.modResults.language !== "kt") {
      throw new Error(
        `withHealthConnectPermissionDelegate expects a Kotlin MainActivity (found: ${config.modResults.language}). ` +
          "This project always generates Kotlin on Expo SDK 54+; add a Java variant here if that ever changes.",
      );
    }
    config.modResults.contents = applyHealthConnectPermissionDelegate(config.modResults.contents);
    return config;
  });
}

module.exports = withHealthConnectPermissionDelegate;
module.exports.applyHealthConnectPermissionDelegate = applyHealthConnectPermissionDelegate;
