import assert from "node:assert/strict";
import { test } from "node:test";
import { applyHealthConnectPermissionDelegate } from "../plugins/withHealthConnectPermissionDelegate";

// Real content generated by `expo prebuild` for this project (Expo SDK 54,
// New Architecture). react-native-health-connect's requestPermission()
// crashes at runtime (kotlin.UninitializedPropertyAccessException: lateinit
// property requestPermission has not been initialized) unless
// HealthConnectPermissionDelegate.setPermissionDelegate(this) runs in
// onCreate — the library's own Expo config plugin never adds this, since it
// only patches AndroidManifest.xml. See
// https://github.com/matinzd/react-native-health-connect/issues/114.
const MAIN_ACTIVITY_KT = `package com.gamma.companion

import android.os.Build
import android.os.Bundle

import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate

import expo.modules.ReactActivityDelegateWrapper

class MainActivity : ReactActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    // Set the theme to AppTheme BEFORE onCreate to support
    // coloring the background, status bar, and navigation bar.
    // This is required for expo-splash-screen.
    setTheme(R.style.AppTheme);
    super.onCreate(null)
  }

  override fun getMainComponentName(): String = "main"
}
`;

test("adds the HealthConnectPermissionDelegate import after the Bundle import", () => {
  const out = applyHealthConnectPermissionDelegate(MAIN_ACTIVITY_KT);
  assert.match(
    out,
    /import android\.os\.Bundle\n[\s\S]*import dev\.matinzd\.healthconnect\.permissions\.HealthConnectPermissionDelegate/,
  );
});

test("registers the permission delegate right after super.onCreate(...)", () => {
  const out = applyHealthConnectPermissionDelegate(MAIN_ACTIVITY_KT);
  assert.match(
    out,
    /super\.onCreate\(null\)\n[\s\S]*HealthConnectPermissionDelegate\.setPermissionDelegate\(this\)/,
  );
});

test("is idempotent — applying twice does not duplicate either insertion", () => {
  const once = applyHealthConnectPermissionDelegate(MAIN_ACTIVITY_KT);
  const twice = applyHealthConnectPermissionDelegate(once);
  assert.equal(twice, once);

  const importCount = (
    twice.match(/import dev\.matinzd\.healthconnect\.permissions\.HealthConnectPermissionDelegate/g) ?? []
  ).length;
  const callCount = (
    twice.match(/HealthConnectPermissionDelegate\.setPermissionDelegate\(this\)/g) ?? []
  ).length;
  assert.equal(importCount, 1);
  assert.equal(callCount, 1);
});

test("throws a clear error when MainActivity.kt doesn't look like the expected Expo template", () => {
  const unexpected = `package com.gamma.companion\n\nclass MainActivity {\n}\n`;
  assert.throws(() => applyHealthConnectPermissionDelegate(unexpected));
});
